<a href="https://colab.research.google.com/github/lnikam1811/Python-Numerical-Methods/blob/master/exercis_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("I love Python!")

I love Python!


In [3]:
s = "S"
w = "Hello world"
type(s)

str

In [5]:
type(w)

str

In [6]:
# Empty string is a str
s = ""
type(s)

str

In [7]:
len(w)

11

In [13]:
w[::2]

'Hlowrd'

In [19]:
'don\'t'

# Concatenation
str_a = "I love Python!"
str_b = " You too!"

print(str_a + str_b)

# Converting to str data type
x = 1
type(str(x))

I love Python! You too!


str

In [20]:
w.upper()

'HELLO WORLD'

In [23]:
w.count("o")

2

In [25]:
w.replace("world", "Nik")

'Hello Nik'

In [26]:
name = "UC Berkeley"
country = "USA"
print(f"{name} is a great school in {country}")

UC Berkeley is a great school in USA


In [27]:
list_1 = [1,2,3]
list_1

[1, 2, 3]

In [33]:
len(list_1)

3

In [37]:
list_1.append(55)
list_1

[1, 2, 3, 55, 55, 55, 55]

In [40]:
list_1.remove(55)
list_1

[1, 2, 3, 55]

In [52]:
list_1.remove("Center")
list_1

[1, 2, 'Center', 3, 55]

In [53]:
del list_1[2]

list_1


[1, 2, 3, 55]

In [54]:
55 in list_1

True

In [55]:
list("My name is Nik")

['M', 'y', ' ', 'n', 'a', 'm', 'e', ' ', 'i', 's', ' ', 'N', 'i', 'k']

In [58]:
import numpy as np

x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
z = np.arange(1,2000,50)
z

array([   1,   51,  101,  151,  201,  251,  301,  351,  401,  451,  501,
        551,  601,  651,  701,  751,  801,  851,  901,  951, 1001, 1051,
       1101, 1151, 1201, 1251, 1301, 1351, 1401, 1451, 1501, 1551, 1601,
       1651, 1701, 1751, 1801, 1851, 1901, 1951])

In [63]:
u = np.linspace(1,2000,10)
u

array([1.00000000e+00, 2.23111111e+02, 4.45222222e+02, 6.67333333e+02,
       8.89444444e+02, 1.11155556e+03, 1.33366667e+03, 1.55577778e+03,
       1.77788889e+03, 2.00000000e+03])

In [64]:
l = np.ones((2,3))
l

array([[1., 1., 1.],
       [1., 1., 1.]])

In [65]:
whos

Variable   Type       Data/Info
-------------------------------
country    str        USA
l          ndarray    2x3: 6 elems, type `float64`, 48 bytes
list_1     list       n=4
name       str        UC Berkeley
np         module     <module 'numpy' from '/us<...>kages/numpy/__init__.py'>
s          str        
str_a      str        I love Python!
str_b      str         You too!
u          ndarray    10: 10 elems, type `float64`, 80 bytes
w          str        Hello world
x          ndarray    2x3: 6 elems, type `int64`, 48 bytes
z          ndarray    40: 40 elems, type `int64`, 320 bytes


"python" in "python is great!"

In [68]:
array_a = np.array([-1,0,1,2,0,3])

array_a > 0

array([False, False,  True,  True, False,  True])

In [72]:
y = np.array([[3,5,3],[2,2,5],[3,8,9]])
y.T

array([[3, 2, 3],
       [5, 2, 8],
       [3, 5, 9]])