<a href="https://colab.research.google.com/github/lnikam1811/Python-Numerical-Methods/blob/master/exercis_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("I love Python!")

I love Python!


In [ ]:
s = "S"
w = "Hello world"
type(s)

str

In [ ]:
type(w)

str

In [ ]:
# Empty string is a str
s = ""
type(s)

str

In [ ]:
len(w)

11

In [ ]:
w[::2]

'Hlowrd'

In [ ]:
'don\'t'

# Concatenation
str_a = "I love Python!"
str_b = " You too!"

print(str_a + str_b)

# Converting to str data type
x = 1
type(str(x))

I love Python! You too!


str

In [ ]:
w.upper()

'HELLO WORLD'

In [ ]:
w.count("o")

2

In [ ]:
w.replace("world", "Nik")

'Hello Nik'

In [ ]:
name = "UC Berkeley"
country = "USA"
print(f"{name} is a great school in {country}")

UC Berkeley is a great school in USA


In [ ]:
list_1 = [1,2,3]
list_1

[1, 2, 3]

In [ ]:
len(list_1)

3

In [ ]:
list_1.append(55)
list_1

[1, 2, 3, 55, 55, 55, 55]

In [ ]:
list_1.remove(55)
list_1

[1, 2, 3, 55]

In [ ]:
list_1.remove("Center")
list_1

[1, 2, 'Center', 3, 55]

In [ ]:
del list_1[2]

list_1


[1, 2, 3, 55]

In [ ]:
55 in list_1

True

In [ ]:
list("My name is Nik")

['M', 'y', ' ', 'n', 'a', 'm', 'e', ' ', 'i', 's', ' ', 'N', 'i', 'k']

In [ ]:
import numpy as np

x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
z = np.arange(1,2000,50)
z

array([   1,   51,  101,  151,  201,  251,  301,  351,  401,  451,  501,
        551,  601,  651,  701,  751,  801,  851,  901,  951, 1001, 1051,
       1101, 1151, 1201, 1251, 1301, 1351, 1401, 1451, 1501, 1551, 1601,
       1651, 1701, 1751, 1801, 1851, 1901, 1951])

In [ ]:
u = np.linspace(1,2000,10)
u

array([1.00000000e+00, 2.23111111e+02, 4.45222222e+02, 6.67333333e+02,
       8.89444444e+02, 1.11155556e+03, 1.33366667e+03, 1.55577778e+03,
       1.77788889e+03, 2.00000000e+03])

In [ ]:
l = np.ones((2,3))
l

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
whos

Variable   Type       Data/Info
-------------------------------
country    str        USA
l          ndarray    2x3: 6 elems, type `float64`, 48 bytes
list_1     list       n=4
name       str        UC Berkeley
np         module     <module 'numpy' from '/us<...>kages/numpy/__init__.py'>
s          str        
str_a      str        I love Python!
str_b      str         You too!
u          ndarray    10: 10 elems, type `float64`, 80 bytes
w          str        Hello world
x          ndarray    2x3: 6 elems, type `int64`, 48 bytes
z          ndarray    40: 40 elems, type `int64`, 320 bytes


In [ ]:
array_a = np.array([-1,0,1,2,0,3])

array_a > 0

array([False, False,  True,  True, False,  True])

In [ ]:
y = np.array([[3,5,3],[2,2,5],[3,8,9]])
y.T

array([[3, 2, 3],
       [5, 2, 8],
       [3, 5, 9]])

In [1]:
"python" in "python is great!"

True

In [4]:
list_a = [1,8,9,15]

list_a.insert(1,2)
list_a


[1, 2, 8, 9, 15]

In [5]:
list_a.append(4)
list_a

[1, 2, 8, 9, 15, 4]

In [6]:
list_a.sort()
list_a

[1, 2, 4, 8, 9, 15]

In [8]:
tuple_a = ("One", 1)
tuple_a

('One', 1)

In [9]:
tuple_a[1]

1

In [10]:
t = (2,3,2,3,1,2,5)
s = set(t)
s

{1, 2, 3, 5}

In [13]:
set_a = {2,3,2}
set_b = {1,2,3}

uni = set_a.union(set_b)
intersect = set_a.intersection(set_b)
diff = set_b.difference(set_a)
uni, intersect, diff

({1, 2, 3}, {2, 3}, {1})

In [14]:
dict = {'A':'a', 'B':'b','C':'c'}

dict.keys()

dict_keys(['A', 'B', 'C'])

In [15]:
'B' in dict

True

In [17]:
import numpy as np
np.linspace(-10,10,100)

array([-10.        ,  -9.7979798 ,  -9.5959596 ,  -9.39393939,
        -9.19191919,  -8.98989899,  -8.78787879,  -8.58585859,
        -8.38383838,  -8.18181818,  -7.97979798,  -7.77777778,
        -7.57575758,  -7.37373737,  -7.17171717,  -6.96969697,
        -6.76767677,  -6.56565657,  -6.36363636,  -6.16161616,
        -5.95959596,  -5.75757576,  -5.55555556,  -5.35353535,
        -5.15151515,  -4.94949495,  -4.74747475,  -4.54545455,
        -4.34343434,  -4.14141414,  -3.93939394,  -3.73737374,
        -3.53535354,  -3.33333333,  -3.13131313,  -2.92929293,
        -2.72727273,  -2.52525253,  -2.32323232,  -2.12121212,
        -1.91919192,  -1.71717172,  -1.51515152,  -1.31313131,
        -1.11111111,  -0.90909091,  -0.70707071,  -0.50505051,
        -0.3030303 ,  -0.1010101 ,   0.1010101 ,   0.3030303 ,
         0.50505051,   0.70707071,   0.90909091,   1.11111111,
         1.31313131,   1.51515152,   1.71717172,   1.91919192,
         2.12121212,   2.32323232,   2.52525253,   2.72

In [23]:
y = np.array([[3,5,3],[2,2,5],[3,8,9]])
y

array([[3, 5, 3],
       [2, 2, 5],
       [3, 8, 9]])

In [28]:
np.zeros([2,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
whos

Variable    Type       Data/Info
--------------------------------
dict        dict       n=3
diff        set        {1}
intersect   set        {2, 3}
list_a      list       n=6
np          module     <module 'numpy' from '/us<...>kages/numpy/__init__.py'>
s           set        {1, 2, 3, 5}
set_a       set        {2, 3}
set_b       set        {1, 2, 3}
t           tuple      n=7
tuple_a     tuple      n=2
uni         set        {1, 2, 3}
y           ndarray    3x3: 9 elems, type `int64`, 72 bytes


In [32]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [33]:
whos


Interactive namespace is empty.
