<a href="https://colab.research.google.com/github/lnikam1811/Python-Numerical-Methods/blob/master/Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Functions

In [ ]:
type(len)

builtin_function_or_method

In [ ]:
import numpy as np

np.linspace?

In [ ]:
def my_adder(a, b, c):
  """
  Function to sum the 3 numbers
  Input: 3 numbers a, b, c
  Output: The sum of a, b, and c
  author:
  date:
  """
  # This is the summation
  out = a + b + c

  return out

In [ ]:
help(my_adder)

Help on function my_adder in module __main__:

my_adder(a, b, c)
    Function to sum the 3 numbers
    Input: 3 numbers a, b, c
    Output: The sum of a, b, and c
    author:
    date:



In [ ]:
def my_test(a, b):
    x = a + b
    y = x * b
    z = a + b

    m = 2

    print(f'Within function: x={x}, y={y}, z={z}')
    return x, y

In [ ]:
a = 2
b = 3
z = 1
y, x = my_test(b, a)

print(f'Outside function: x={x}, y={y}, z={z}')

Within function: x=5, y=10, z=5
Outside function: x=10, y=5, z=1


In [ ]:
n = 42

def func():
    global n
    print(f'Within function: n is {n}')
    n = 3
    print(f'Within function: change n to {n}')

func()
print(f'Outside function: Value of n is {n}')

Within function: n is 42
Within function: change n to 3
Outside function: Value of n is 3


# Nested functions

In [ ]:
import numpy as np

def my_dist_xyz(x,y,z):
  """
  x, y, z are 2D coordinates contained in tuple
  output:
  d - list, where
  d[0] is the distance between x and y
  d[1] is the distance between x and z
  d[2] is the distance between y and z
  """
  def my_dist(x,y):
    """
    subfunction for my_dist_xyz
    Output is the distance between x and y, computed using the
    distance formula.
    """
    out = np.sqrt((x[0]-y[0])**2+(x[1]-y[1])**2)
    return out

  d0 = my_dist(x,y)
  d1 = my_dist(x,z)
  d2 = my_dist(y,z)

  return [d0, d1, d2]

In [ ]:
d = my_dist_xyz((0, 0), (0, 1), (1, 1))
print(d)
d = my_dist((0, 0), (0, 1))

[1.0, 1.4142135623730951, 1.0]


NameError: ignored

In [ ]:
import numpy as np

def my_dist_xyz(x, y, z):
    """
    x, y, z are 2D coordinates contained in a tuple
    output:
    d - list, where
        d[0] is the distance between x and y
        d[1] is the distance between x and z
        d[2] is the distance between y and z
    """

    d0 = np.sqrt((x[0]-y[0])**2+(x[1]-y[1])**2)
    d1 = np.sqrt((x[0]-z[0])**2+(x[1]-z[1])**2)
    d2 = np.sqrt((y[0]-z[0])**2+(y[1]-z[1])**2)

    return [d0, d1, d2]

# Lambda Functions

In [ ]:
# Define a lambda function, which square the input number, and call the function with 2 and 5

square = lambda x: x**2

print(square(10))
print(square(17))

100
289


In [ ]:
def square(x):
  return x**2

my_adder = lambda x,y: x+y

print(my_adder(2,4))

6


In [ ]:
sorted([(1,2),(2,0),(4,1)], key=lambda x: x[1])

[(2, 0), (4, 1), (1, 2)]

# Functions as Arguments to Functions

In [ ]:
f = max

def my_fun_plus_one(f, x):
  return f(x) + 1

print(my_fun_plus_one(np.sin, np.pi/2))
print(my_fun_plus_one(np.cos, np.pi/2))
print(my_fun_plus_one(np.sqrt, 25))

2.0
1.0
6.0


In [ ]:
print(my_fun_plus_one(lambda x: x + 2, 2))

5


# Problems

### 1. Recall that the hyperbolic sine, denoted by $sinh$, is $\frac{exp(x)-exp(-x)}{2}$. Write a function my_sinh(x), where the output $y$ is the hyperbolic sine computed on $x$. Assume that x is a 1 by 1 float.

In [ ]:

def my_sinh(x):
  return (np.exp(x)-np.exp(-x))/(2)

print(my_sinh(2))

3.626860407847019


### 2. Write a function my_checker_board(n), where the output m is an n x n array.

In [ ]:
def my_checker_board(n):
  x = np.zeros((n,n), dtype=int)
  x[::2, ::2] = 1
  x[1::2, 1::2] = 1
  return x


print(my_checker_board(5))

[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]


In [ ]:
def my_triangle(b,h):
  area = 0.5*b*h
  return area